module TimeSeriesAnalyzer
  VERSION: String

  class TimeSeries
    attr_accessor data: Array[Float]
    attr_accessor timestamps: Array[Float]
    attr_accessor period: Integer

    def initialize: (data: Array[Float], timestamps: Array[Float], period: Integer) -> void

    def self.load_from_csv: (file_path: String, period: Integer) -> void

    def exponential_smoothing: (alpha: Float) -> void

    def moving_average: (window_size: Integer) -> TimeSeries

    def plot: (file_name: String, title: String) -> void

    private

    def draw_plot: (data: Array[Float], timestamps: Array[Float], title: String, file_name: String) -> void
  end
end
